# Classification Exercise

We'll be working with some California Census Data, we'll be trying to use various features of an individual to predict what class of income they belogn in (>50k or <=50k). 

Here is some information about the data:

<table>
<thead>
<tr>
<th>Column Name</th>
<th>Type</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr>
<td>age</td>
<td>Continuous</td>
<td>The age of the individual</td>
</tr>
<tr>
<td>workclass</td>
<td>Categorical</td>
<td>The type of employer the  individual has (government,  military, private, etc.).</td>
</tr>
<tr>
<td>fnlwgt</td>
<td>Continuous</td>
<td>The number of people the census  takers believe that observation  represents (sample weight). This  variable will not be used.</td>
</tr>
<tr>
<td>education</td>
<td>Categorical</td>
<td>The highest level of education  achieved for that individual.</td>
</tr>
<tr>
<td>education_num</td>
<td>Continuous</td>
<td>The highest level of education in  numerical form.</td>
</tr>
<tr>
<td>marital_status</td>
<td>Categorical</td>
<td>Marital status of the individual.</td>
</tr>
<tr>
<td>occupation</td>
<td>Categorical</td>
<td>The occupation of the individual.</td>
</tr>
<tr>
<td>relationship</td>
<td>Categorical</td>
<td>Wife, Own-child, Husband,  Not-in-family, Other-relative,  Unmarried.</td>
</tr>
<tr>
<td>race</td>
<td>Categorical</td>
<td>White, Asian-Pac-Islander,  Amer-Indian-Eskimo, Other, Black.</td>
</tr>
<tr>
<td>gender</td>
<td>Categorical</td>
<td>Female, Male.</td>
</tr>
<tr>
<td>capital_gain</td>
<td>Continuous</td>
<td>Capital gains recorded.</td>
</tr>
<tr>
<td>capital_loss</td>
<td>Continuous</td>
<td>Capital Losses recorded.</td>
</tr>
<tr>
<td>hours_per_week</td>
<td>Continuous</td>
<td>Hours worked per week.</td>
</tr>
<tr>
<td>native_country</td>
<td>Categorical</td>
<td>Country of origin of the  individual.</td>
</tr>
<tr>
<td>income</td>
<td>Categorical</td>
<td>"&gt;50K" or "&lt;=50K", meaning  whether the person makes more  than \$50,000 annually.</td>
</tr>
</tbody>
</table>

## Follow the Directions in Bold. If you get stuck, check out the solutions lecture.

### THE DATA

** Read in the census_data.csv data with pandas**

In [1]:
import pandas as pd

In [3]:
census = pd.read_csv('census_data.csv')
census.head()

,age,workclass,education,education_num,marital_status,occupation,relationship,race,gender,capital_gain,capital_loss,hours_per_week,native_country,income_bracket
0,39,State-gov,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

** TensorFlow won't be able to understand strings as labels, you'll need to use pandas .apply() method to apply a custom function that converts them to 0s and 1s. This might be hard if you aren't very familiar with pandas, so feel free to take a peek at the solutions for this part.**

** Convert the Label column to 0s and 1s instead of strings.**

In [4]:
census['income_bracket'].unique()

array([' <=50K', ' >50K'], dtype=object)

In [5]:
def label_fix(label):
    if label == '<=50K':
        return 0
    else:
        return 1

In [6]:
census['income_bracket'] = census['income_bracket'].apply(label_fix)

In [7]:
census.head()

,age,workclass,education,education_num,marital_status,occupation,relationship,race,gender,capital_gain,capital_loss,hours_per_week,native_country,income_bracket
0,39,State-gov,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,1
1,50,Self-emp-not-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,1
2,38,Private,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,1
3,53,Private,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,1
4,28,Private,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,1

### Perform a Train Test Split on the Data

In [16]:
from sklearn.model_selection import train_test_split

In [11]:
X_data = census.drop(['income_bracket'],axis=1)
X_data.head()

,age,workclass,education,education_num,marital_status,occupation,relationship,race,gender,capital_gain,capital_loss,hours_per_week,native_country
0,39,State-gov,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States
1,50,Self-emp-not-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States
2,38,Private,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States
3,53,Private,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States
4,28,Private,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba

In [12]:
y_label = census['income_bracket']
y_label.head()

0    1
1    1
2    1
3    1
4    1
Name: income_bracket, dtype: int64

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X_data, y_label, test_size=0.3, random_state=101)

### Create the Feature Columns for tf.esitmator

** Take note of categorical vs continuous values! **

In [19]:
census.columns

Index(['age', 'workclass', 'education', 'education_num', 'marital_status',
       'occupation', 'relationship', 'race', 'gender', 'capital_gain',
       'capital_loss', 'hours_per_week', 'native_country', 'income_bracket'],
      dtype='object')

** Import Tensorflow **

In [18]:
import tensorflow as tf

** Create the tf.feature_columns for the categorical values. Use vocabulary lists or just use hash buckets. **

In [25]:
workclass = tf.feature_column.categorical_column_with_hash_bucket('workclass',hash_bucket_size=50)
education = tf.feature_column.categorical_column_with_hash_bucket('education',hash_bucket_size=50)
marital_status = tf.feature_column.categorical_column_with_hash_bucket('marital_status',hash_bucket_size=10)
occupation = tf.feature_column.categorical_column_with_hash_bucket('occupation',hash_bucket_size=500)
relationship = tf.feature_column.categorical_column_with_hash_bucket('relationship',hash_bucket_size=20)
race = tf.feature_column.categorical_column_with_hash_bucket('race',hash_bucket_size=10)
gender = tf.feature_column.categorical_column_with_vocabulary_list('gender',['Male','Female'])
native_country = tf.feature_column.categorical_column_with_hash_bucket('native_country',hash_bucket_size=200)

** Create the continuous feature_columns for the continuous values using numeric_column **

In [26]:
age = tf.feature_column.numeric_column('age')
education_num = tf.feature_column.numeric_column('education_num')
capital_gain = tf.feature_column.numeric_column('capital_gain')
capital_loss = tf.feature_column.numeric_column('capital_loss')
hours_per_week = tf.feature_column.numeric_column('hours_per_week')

** Put all these variables into a single list with the variable name feat_cols **

In [27]:
feat_cols = [age,workclass,education,education_num,
             marital_status,occupation,relationship,
             race,gender,capital_gain,capital_loss,
             hours_per_week,native_country]

### Create Input Function

** Batch_size is up to you. But do make sure to shuffle!**

In [57]:
input_func = tf.estimator.inputs.pandas_input_fn(x=X_train,y=y_train,batch_size=100,num_epochs=None,shuffle=True)

#### Create your model with tf.estimator

**Create a LinearClassifier.(If you want to use a DNNClassifier, keep in mind you'll need to create embedded columns out of the cateogrical feature that use strings, check out the previous lecture on this for more info.)**

In [30]:
model = tf.estimator.LinearClassifier(feature_columns=feat_cols)

INFO:tensorflow:Using default config.
WARNING:tensorflow:Using temporary folder as model directory: /tmp/tmp344r_g91
INFO:tensorflow:Using config: {'_model_dir': '/tmp/tmp344r_g91', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f60123c1208>, '_task_type': 'worker', '_task_id': 0, '_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}

** Train your model on the data, for at least 5000 steps. **

In [58]:
model.train(input_fn=input_func,steps=10000)

INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Restoring parameters from /tmp/tmp344r_g91/model.ckpt-5000
INFO:tensorflow:Saving checkpoints for 5001 into /tmp/tmp344r_g91/model.ckpt.
INFO:tensorflow:loss = 0.000437634, step = 5001
INFO:tensorflow:global_step/sec: 168.454
INFO:tensorflow:loss = 0.000200296, step = 5101 (0.595 sec)
INFO:tensorflow:global_step/sec: 193.862
INFO:tensorflow:loss = 0.000247214, step = 5201 (0.519 sec)
INFO:tensorflow:global_step/sec: 184.751
INFO:tensorflow:loss = 0.000190145, step = 5301 (0.546 sec)
INFO:tensorflow:global_step/sec: 161.028
INFO:tensorflow:loss = 0.000828303, step = 5401 (0.621 sec)
INFO:tensorflow:global_step/sec: 182.667
INFO:tensorflow:loss = 0.000242714, step = 5501 (0.541 sec)
INFO:tensorflow:global_step/sec: 169.503
INFO:tensorflow:loss = 5.81001e-05, step = 5601 (0.592 sec)
INFO:tensorflow:global_step/sec: 188.963
INFO:tensorflow:loss = 2.9047e-05, step = 5701 (0.529 sec)
INFO:tensorflow:global_step/sec: 189.593
INFO:tensorflow:loss = 0.000129695, step = 5801 (0.527 sec)
INFO:tensorflow:global_step/sec: 174.155
INFO:tensorflow:loss = 0.000269636, step = 5901 (0.587 sec)
INFO:tensorflow:global_step/sec: 145.737
INFO:tensorflow:loss = 1.78929e-05, step = 6001 (0.671 sec)
INFO:tensorflow:global_step/sec: 153.189
INFO:tensorflow:loss = 8.98283e-05, step = 6101 (0.662 sec)
INFO:tensorflow:global_step/sec: 168.989
INFO:tensorflow:loss = 6.15514e-05, step = 6201 (0.581 sec)
INFO:tensorflow:global_step/sec: 193.396
INFO:tensorflow:loss = 0.000174111, step = 6301 (0.519 sec)
INFO:tensorflow:global_step/sec: 189.495
INFO:tensorflow:loss = 0.000527057, step = 6401 (0.531 sec)
INFO:tensorflow:global_step/sec: 204.87
INFO:tensorflow:loss = 9.95911e-06, step = 6501 (0.490 sec)
INFO:tensorflow:global_step/sec: 183.904
INFO:tensorflow:loss = 1.11122e-05, step = 6601 (0.541 sec)
INFO:tensorflow:global_step/sec: 180.488
INFO:tensorflow:loss = 3.69377e-05, step = 6701 (0.555 sec)
INFO:tensorflow:global_step/sec: 182.895
INFO:tensorflow:loss = 0.000105884, step = 6801 (0.547 sec)
INFO:tensorflow:global_step/sec: 183.068
INFO:tensorflow:loss = 0.000195476, step = 6901 (0.546 sec)
INFO:tensorflow:global_step/sec: 187.505
INFO:tensorflow:loss = 0.000231572, step = 7001 (0.532 sec)
INFO:tensorflow:global_step/sec: 177.87
INFO:tensorflow:loss = 4.76136e-05, step = 7101 (0.569 sec)
INFO:tensorflow:global_step/sec: 156.751
INFO:tensorflow:loss = 3.85508e-05, step = 7201 (0.628 sec)
INFO:tensorflow:global_step/sec: 171.919
INFO:tensorflow:loss = 0.000133125, step = 7301 (0.585 sec)
INFO:tensorflow:global_step/sec: 196.289
INFO:tensorflow:loss = 0.000110317, step = 7401 (0.510 sec)
INFO:tensorflow:global_step/sec: 148.269
INFO:tensorflow:loss = 0.000186618, step = 7501 (0.677 sec)
INFO:tensorflow:global_step/sec: 181.897
INFO:tensorflow:loss = 1.5583e-05, step = 7601 (0.549 sec)
INFO:tensorflow:global_step/sec: 190.801
INFO:tensorflow:loss = 3.84632e-05, step = 7701 (0.523 sec)
INFO:tensorflow:global_step/sec: 191.423
INFO:tensorflow:loss = 3.09071e-05, step = 7801 (0.520 sec)
INFO:tensorflow:global_step/sec: 186.949
INFO:tensorflow:loss = 0.000170083, step = 7901 (0.536 sec)
INFO:tensorflow:global_step/sec: 198.059
INFO:tensorflow:loss = 0.000129562, step = 8001 (0.507 sec)
INFO:tensorflow:global_step/sec: 196.943
INFO:tensorflow:loss = 5.89572e-05, step = 8101 (0.507 sec)
INFO:tensorflow:global_step/sec: 202.33
INFO:tensorflow:loss = 2.36876e-05, step = 8201 (0.492 sec)
INFO:tensorflow:global_step/sec: 201.686
INFO:tensorflow:loss = 0.000398803, step = 8301 (0.498 sec)
INFO:tensorflow:global_step/sec: 164.391
INFO:tensorflow:loss = 3.11473e-05, step = 8401 (0.613 sec)
INFO:tensorflow:global_step/sec: 150.404
INFO:tensorflow:loss = 0.000105692, step = 8501 (0.659 sec)
INFO:tensorflow:global_step/sec: 185.067
INFO:tensorflow:loss = 0.000603362, step = 8601 (0.541 sec)
INFO:tensorflow:global_step/sec: 191.158
INFO:tensorflow:loss = 8.57214e-06, step = 8701 (0.523 sec)
INFO:tensorflow:global_step/sec: 187.006
INFO:tensorflow:loss = 1.34637e-05, step = 8801 (0.537 sec)
INFO:tensorflow:global_step/sec: 168.541
INFO:tensorflow:loss = 0.000136887, step = 8901 (0.593 sec)
INFO:tensorflow:global_step/sec: 150.509
INFO:tensorflow:loss = 6.29985e-05, step = 9001 (0.658 sec)
INFO:tensorflow:global_step/sec: 191.044
INFO:tensorflow:loss = 1.19047e-05, step = 9101 (0.523 sec)
INFO:tensorflow:global_step/sec: 190.738
INFO:tensorflow:loss = 0.000163675, step = 9201 (0.524 sec)
INFO:tensorflow:global_step/sec: 189.676
INFO:tensorflow:loss = 5.27183e-05, step = 9301 (0.532 sec)
INFO:tensorflow:global_step/sec: 194.431
INFO:tensorflow:loss = 7.58371e-05, step = 9401 (0.515 sec)
INFO:tensorflow:global_step/sec: 181.108
INFO:tensorflow:loss = 0.000111391, step = 9501 (0.551 sec)
INFO:tensorflow:global_step/sec: 175.818
INFO:tensorflow:loss = 4.63413e-05, step = 9601 (0.564 sec)
INFO:tensorflow:global_step/sec: 180.329
INFO:tensorflow:loss = 7.39784e-05, step = 9701 (0.559 sec)
INFO:tensorflow:global_step/sec: 187.4
INFO:tensorflow:loss = 0.000299812, step = 9801 (0.533 sec)
INFO:tensorflow:global_step/sec: 188.632
INFO:tensorflow:loss = 0.000231718, step = 9901 (0.528 sec)
INFO:tensorflow:global_step/sec: 172.222
INFO:tensorflow:loss = 2.97873e-05, step = 10001 (0.581 sec)
INFO:tensorflow:global_step/sec: 135.133
INFO:tensorflow:loss = 0.000106427, step = 10101 (0.743 sec)
INFO:tensorflow:global_step/sec: 144.909
INFO:tensorflow:loss = 7.66984e-05, step = 10201 (0.685 sec)
INFO:tensorflow:global_step/sec: 154.196
INFO:tensorflow:loss = 0.000126284, step = 10301 (0.657 sec)
INFO:tensorflow:global_step/sec: 176.011
INFO:tensorflow:loss = 0.000138187, step = 10401 (0.568 sec)
INFO:tensorflow:global_step/sec: 177.159
INFO:tensorflow:loss = 0.000260025, step = 10501 (0.569 sec)
INFO:tensorflow:global_step/sec: 137.841
INFO:tensorflow:loss = 6.21561e-05, step = 10601 (0.725 sec)
INFO:tensorflow:global_step/sec: 174.947
INFO:tensorflow:loss = 4.76441e-06, step = 10701 (0.560 sec)
INFO:tensorflow:global_step/sec: 153.376
INFO:tensorflow:loss = 9.21302e-06, step = 10801 (0.662 sec)
INFO:tensorflow:global_step/sec: 175.777
INFO:tensorflow:loss = 0.000118145, step = 10901 (0.564 sec)
INFO:tensorflow:global_step/sec: 162.943
INFO:tensorflow:loss = 0.000135706, step = 11001 (0.610 sec)
INFO:tensorflow:global_step/sec: 169.99
INFO:tensorflow:loss = 1.08564e-05, step = 11101 (0.586 sec)
INFO:tensorflow:global_step/sec: 156.616
INFO:tensorflow:loss = 0.00017499, step = 11201 (0.642 sec)
INFO:tensorflow:global_step/sec: 163.477
INFO:tensorflow:loss = 9.90905e-05, step = 11301 (0.608 sec)
INFO:tensorflow:global_step/sec: 193.613
INFO:tensorflow:loss = 1.49132e-05, step = 11401 (0.516 sec)
INFO:tensorflow:global_step/sec: 192.469
INFO:tensorflow:loss = 0.000133824, step = 11501 (0.523 sec)
INFO:tensorflow:global_step/sec: 180.89
INFO:tensorflow:loss = 8.82971e-05, step = 11601 (0.557 sec)
INFO:tensorflow:global_step/sec: 175.308
INFO:tensorflow:loss = 2.94323e-05, step = 11701 (0.563 sec)
INFO:tensorflow:global_step/sec: 165.428
INFO:tensorflow:loss = 3.77256e-05, step = 11801 (0.609 sec)
INFO:tensorflow:global_step/sec: 164.927
INFO:tensorflow:loss = 3.26956e-05, step = 11901 (0.606 sec)
INFO:tensorflow:global_step/sec: 192.253
INFO:tensorflow:loss = 1.73405e-05, step = 12001 (0.520 sec)
INFO:tensorflow:global_step/sec: 170.579
INFO:tensorflow:loss = 8.44914e-05, step = 12101 (0.586 sec)
INFO:tensorflow:global_step/sec: 163.846
INFO:tensorflow:loss = 2.96647e-05, step = 12201 (0.615 sec)
INFO:tensorflow:global_step/sec: 165.288
INFO:tensorflow:loss = 3.69901e-05, step = 12301 (0.599 sec)
INFO:tensorflow:global_step/sec: 160.507
INFO:tensorflow:loss = 7.44807e-05, step = 12401 (0.625 sec)
INFO:tensorflow:global_step/sec: 186.568
INFO:tensorflow:loss = 6.85729e-05, step = 12501 (0.536 sec)
INFO:tensorflow:global_step/sec: 188.969
INFO:tensorflow:loss = 2.05189e-05, step = 12601 (0.529 sec)
INFO:tensorflow:global_step/sec: 185.634
INFO:tensorflow:loss = 0.000316998, step = 12701 (0.540 sec)
INFO:tensorflow:global_step/sec: 172.21
INFO:tensorflow:loss = 0.000101416, step = 12801 (0.581 sec)
INFO:tensorflow:global_step/sec: 168.046
INFO:tensorflow:loss = 2.68187e-05, step = 12901 (0.593 sec)

INFO:tensorflow:global_step/sec: 191.519
INFO:tensorflow:loss = 2.39596e-05, step = 13001 (0.518 sec)
INFO:tensorflow:global_step/sec: 186.045
INFO:tensorflow:loss = 1.46502e-05, step = 13101 (0.538 sec)
INFO:tensorflow:global_step/sec: 193.485
INFO:tensorflow:loss = 1.6492e-05, step = 13201 (0.517 sec)
INFO:tensorflow:global_step/sec: 194.677
INFO:tensorflow:loss = 1.67833e-05, step = 13301 (0.520 sec)
INFO:tensorflow:global_step/sec: 196.944
INFO:tensorflow:loss = 1.63918e-05, step = 13401 (0.505 sec)
INFO:tensorflow:global_step/sec: 193.381
INFO:tensorflow:loss = 5.71293e-05, step = 13501 (0.519 sec)
INFO:tensorflow:global_step/sec: 190.334
INFO:tensorflow:loss = 1.53557e-05, step = 13601 (0.528 sec)
INFO:tensorflow:global_step/sec: 200.751
INFO:tensorflow:loss = 6.98028e-05, step = 13701 (0.492 sec)
INFO:tensorflow:global_step/sec: 199.601
INFO:tensorflow:loss = 6.83731e-05, step = 13801 (0.501 sec)
INFO:tensorflow:global_step/sec: 199.275
INFO:tensorflow:loss = 4.38038e-05, step = 13901 (0.502 sec)
INFO:tensorflow:global_step/sec: 207.26
INFO:tensorflow:loss = 6.96462e-05, step = 14001 (0.489 sec)
INFO:tensorflow:global_step/sec: 194.089
INFO:tensorflow:loss = 0.000160981, step = 14101 (0.515 sec)
INFO:tensorflow:global_step/sec: 203.139
INFO:tensorflow:loss = 1.14429e-05, step = 14201 (0.488 sec)
INFO:tensorflow:global_step/sec: 203.09
INFO:tensorflow:loss = 5.04282e-05, step = 14301 (0.490 sec)
INFO:tensorflow:global_step/sec: 201.458
INFO:tensorflow:loss = 0.000119888, step = 14401 (0.496 sec)
INFO:tensorflow:global_step/sec: 203.221
INFO:tensorflow:loss = 3.14695e-06, step = 14501 (0.497 sec)
INFO:tensorflow:global_step/sec: 191.288
INFO:tensorflow:loss = 0.000157926, step = 14601 (0.521 sec)
INFO:tensorflow:global_step/sec: 193.155
INFO:tensorflow:loss = 0.000192248, step = 14701 (0.517 sec)
INFO:tensorflow:global_step/sec: 198.345
INFO:tensorflow:loss = 7.9382e-05, step = 14801 (0.508 sec)
INFO:tensorflow:global_step/sec: 199.295
INFO:tensorflow:loss = 1.1838e-05, step = 14901 (0.503 sec)
INFO:tensorflow:Saving checkpoints for 15000 into /tmp/tmp344r_g91/model.ckpt.
INFO:tensorflow:Loss for final step: 7.36405e-05.

### Evaluation

** Create a prediction input function. Remember to only supprt X_test data and keep shuffle=False. **

In [59]:
pred_input_func = tf.estimator.inputs.pandas_input_fn(x=X_test,batch_size=len(X_test),shuffle=False)

** Use model.predict() and pass in your input function. This will produce a generator of predictions, which you can then transform into a list, with list() **

In [60]:
pred_gen = model.predict(input_fn=pred_input_func)
predictions = list(pred_gen)

INFO:tensorflow:Restoring parameters from /tmp/tmp344r_g91/model.ckpt-15000

** Each item in your list will look like this: **

In [61]:
predictions[0]

{'logits': array([ 23.7388382], dtype=float32),
 'logistic': array([ 1.], dtype=float32),
 'probabilities': array([  4.90177725e-11,   1.00000000e+00], dtype=float32),
 'class_ids': array([1]),
 'classes': array([b'1'], dtype=object)}

** Create a list of only the class_ids key values from the prediction list of dictionaries, these are the predictions you will use to compare against the real y_test values. **

In [62]:
final_preds = [pred['class_ids'][0] for pred in predictions]

In [63]:
final_preds

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 ...]

** Import classification_report from sklearn.metrics and then see if you can figure out how to use it to easily get a full report of your model's performance on the test data. **

In [64]:
from sklearn.metrics import classification_report

In [66]:
print(classification_report(y_test,final_preds))

             precision    recall  f1-score   support

          1       1.00      1.00      1.00      9769

avg / total       1.00      1.00      1.00      9769

# Great Job!